Introducing DemoTemporalTiler
As a general note, the full pipeline is now effective, with the major
restriction that the very last stage (i.e. docker_temporal_tiler.py)
is not stable. The problem is that the docker wrapped postgresql servers
tend to time out and psy2cog get to a grind with a message
     psycopg2.OperationalError: server closed the connection unexpectedly
     This probably means the server terminated abnormally
     before or while processing the request.
Refer to CityTiler remarks:
  https://github.com/VCityTeam/py3dtiles/blob/Tiler/Tilers/CityTiler/database_accesses.py#L49

 - docker_temporal_tiler.py now generates the configuration files.
 - DemoTemporalTiler
 - demo.py: DemoWithDataBases class extracted from Demo class
   demo_3dcitydb_server.py and demo_load_3dcitydb.py changed
   accordingly.
 - demo_load_3dcitydb.py now does some (shallow) check of the
   its execution.
 - DemoExtractBuildingDates now renames the output files in order
   to ingerate the borough and vintages in the filename
 - Added a Docker/CityTiler-DockerContext/CityTilerDBConfigDummy.yml
   empty file in order to allow both
    * the mode were config files are copied at container build time
      (through DockerFile COPY) like ShellScriptCallingDocker does it
    * the mode were config files are copied at run time like
      PythonCallingDocker does it.
 - Docker/CityTiler-DockerContext/entrypoint.py modified to allow for
   mount-point volume transmitted data-bases configuration files.